registry:
  build: ./registry-service
  ports:
    - "1111:1111"
dj:
  build: ./dj-service
  links:
    - registry:registry
location:
  build: ./location-service
  links:
    - registry:registry
event:
  build: ./event-service
  links:
    - registry:registry
event-location:
  build: ./event-location-service
  links:
    - registry:registry
    - event:event-service
    - location:location-service
frontend:
  build: ./frontend-service
  links:
    - registry:registry
    - dj:dj-service
    - location:location-service
    - event:event-service
  ports:
    - "8080:8080"